In [5]:
pip install matplotlib

                                              0.0/7.6 MB ? eta -:--:--
                                              0.0/7.6 MB ? eta -:--:--
                                              0.1/7.6 MB 656.4 kB/s eta 0:00:12
                                              0.1/7.6 MB 819.2 kB/s eta 0:00:10
                                              0.1/7.6 MB 853.3 kB/s eta 0:00:09
     -                                        0.2/7.6 MB 841.6 kB/s eta 0:00:09
     -                                        0.2/7.6 MB 801.7 kB/s eta 0:00:10
     -                                        0.3/7.6 MB 850.6 kB/s eta 0:00:09
     -                                        0.3/7.6 MB 855.7 kB/s eta 0:00:09
     -                                        0.4/7.6 MB 882.8 kB/s eta 0:00:09
     --                                       0.4/7.6 MB 859.0 kB/s eta 0:00:09
     --                                       0.5/7.6 MB 880.6 kB/s eta 0:00:09
     --                                       0.5/7.6 MB 8


[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
pip install pandas

                                              0.0/10.6 MB ? eta -:--:--
                                             0.0/10.6 MB 660.6 kB/s eta 0:00:17
                                             0.0/10.6 MB 660.6 kB/s eta 0:00:17
                                             0.1/10.6 MB 409.6 kB/s eta 0:00:26
                                             0.1/10.6 MB 409.6 kB/s eta 0:00:26
                                             0.1/10.6 MB 403.5 kB/s eta 0:00:27
                                             0.1/10.6 MB 409.6 kB/s eta 0:00:26
                                             0.1/10.6 MB 359.9 kB/s eta 0:00:30
                                             0.1/10.6 MB 370.8 kB/s eta 0:00:29
                                             0.2/10.6 MB 353.1 kB/s eta 0:00:30
                                             0.2/10.6 MB 374.1 kB/s eta 0:00:28
                                             0.2/10.6 MB 366.4 kB/s eta 0:00:29
                                             0.2

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
wordcloud 1.9.2 requires matplotlib, which is not installed.
wordcloud 1.9.2 requires pillow, which is not installed.

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [7]:
data = pd.read_csv("FinalBalancedDataset.csv")

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56745 entries, 0 to 56744
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  56745 non-null  int64 
 1   Toxicity    56745 non-null  int64 
 2   tweet       56745 non-null  object
dtypes: int64(2), object(1)
memory usage: 1.3+ MB


In [9]:
data.head(5)

Unnamed: 0  Toxicity                                              tweet
0           0         0   @user when a father is dysfunctional and is s...
1           1         0  @user @user thanks for #lyft credit i can't us...
2           2         0                                bihday your majesty
3           3         0  #model   i love u take with u all the time in ...
4           4         0             factsguide: society now    #motivation

In [10]:
data = data.drop("Unnamed: 0", axis=1)

In [11]:
data.head(5)

Toxicity                                              tweet
0         0   @user when a father is dysfunctional and is s...
1         0  @user @user thanks for #lyft credit i can't us...
2         0                                bihday your majesty
3         0  #model   i love u take with u all the time in ...
4         0             factsguide: society now    #motivation

In [12]:
data['Toxicity'].value_counts()

Toxicity
0    32592
1    24153
Name: count, dtype: int64

In [17]:
!pip install nltk


[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
                                              0.0/1.5 MB ? eta -:--:--
     -                                        0.1/1.5 MB ? eta -:--:--
     -                                        0.1/1.5 MB ? eta -:--:--
     

In [18]:
import nltk
nltk.download('punkt')
nltk.download('omw-1.4')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
from nltk import WordNetLemmatizer
from nltk import pos_tag, word_tokenize
from nltk.corpus import stopwords as nltk_stopwords
from nltk.corpus import wordnet

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\siman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\siman\AppData\Roaming\nltk_data...
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\siman\AppData\Roaming\nltk_data...
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\siman\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\siman\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


## Lemmatizer
1. Leaves
2. Leafs
Leaf

## Text pre-processing

In [19]:
wordnet_lemmatizer = WordNetLemmatizer()

In [20]:
import re

In [21]:
def prepare_text(text):
    def get_wordnet_pos(treebank_tag):
        if treebank_tag.startswith('J'):
            return wordnet.ADJ
        elif treebank_tag.startswith('V'):
            return wordnet.VERB
        elif treebank_tag.startswith('N'):
            return wordnet.NOUN
        elif treebank_tag.startswith('R'):
            return wordnet.ADV
        else:
            return wordnet.NOUN
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    text = text.split()
    text = ' '.join(text)
    text = word_tokenize(text)
    text = pos_tag(text)
    lemma = []
    for i in text: lemma.append(wordnet_lemmatizer.lemmatize(i[0], pos = get_wordnet_pos(i[1])))
    lemma = ' '.join(lemma)
    return lemma

In [22]:
data['clean_tweets'] = data['tweet'].apply(lambda x: prepare_text(x))

In [23]:
data.head(5)

Toxicity                                              tweet  \
0         0   @user when a father is dysfunctional and is s...   
1         0  @user @user thanks for #lyft credit i can't us...   
2         0                                bihday your majesty   
3         0  #model   i love u take with u all the time in ...   
4         0             factsguide: society now    #motivation   

                                        clean_tweets  
0  user when a father be dysfunctional and be so ...  
1  user user thanks for lyft credit i ca n't use ...  
2                                bihday your majesty  
3      model i love u take with u all the time in ur  
4                  factsguide society now motivation

## Tfidf for features

In [26]:
!pip install scikit-learn


[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip



  Using cached scikit_learn-1.3.2-cp311-cp311-win_amd64.whl (9.2 MB)
                                              0.0/44.1 MB ? eta -:--:--
                                              0.0/44.1 MB ? eta -:--:--
                                             0.1/44.1 MB 656.4 kB/s eta 0:01:08
                                             0.1/44.1 MB 944.1 kB/s eta 0:00:47
                                              0.2/44.1 MB 1.2 MB/s eta 0:00:38
                                              0.3/44.1 MB 1.1 MB/s eta 0:00:40
                                              0.3/44.1 MB 1.2 MB/s eta 0:00:38
                                              0.4/44.1 MB 1.2 MB/s eta 0:00:35
                                              0.4/44.1 MB 1.3 MB/s eta 0:00:34
                                              0.5/44.1 MB 1.2 MB/s eta 0:00:38
                                              0.5/44.1 MB 1.2 MB/s eta 0:00:38
                                              0.6/44.1 MB 1.2 MB/s eta 0:

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve

In [28]:
corpus = data['clean_tweets'].values.astype('U')

In [29]:
stopwords = set(nltk_stopwords.words('english'))

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

# Get English stopwords from NLTK
stop_words = stopwords.words('english')

# Assuming 'corpus' is defined somewhere in your code
count_tf_idf = TfidfVectorizer(stop_words=stop_words)
tf_idf = count_tf_idf.fit_transform(corpus)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\siman\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [34]:
import pickle

In [35]:
pickle.dump(count_tf_idf, open("tf_idf.pkt", "wb"))

In [36]:
tf_idf_train, tf_idf_test, target_train, target_test = train_test_split(
    tf_idf, data['Toxicity'], test_size = 0.8, random_state= 42, shuffle=True
)

## Create a Binary Classification Model

In [37]:
model_bayes = MultinomialNB()

In [38]:
model_bayes = model_bayes.fit(tf_idf_train, target_train)

In [39]:
y_pred_proba = model_bayes.predict_proba(tf_idf_test)[::, 1]

In [40]:
y_pred_proba

array([0.90152453, 0.27916787, 0.79021827, ..., 0.09487729, 0.20555162,
       0.32090192])

In [41]:
fpr, tpr, _ = roc_curve(target_test, y_pred_proba)

In [42]:
final_roc_auc = roc_auc_score(target_test, y_pred_proba)

In [43]:
final_roc_auc

0.9658691315317345

In [44]:
test_text = "I hate you moron"
test_tfidf = count_tf_idf.transform([test_text])
display(model_bayes.predict_proba(test_tfidf))
display(model_bayes.predict(test_tfidf))

array([[0.39920068, 0.60079932]])

array([1], dtype=int64)

## Save the model

In [45]:
pickle.dump(model_bayes, open("toxicity_model.pkt", "wb"))